# Natural Language Processing, Homework 1
 Dr. Sharon Yalov-Handzel

You can submit the homework as *.py or *.ipynb file.  
Answers to theoretical questions can be written in a separate WORD document.

Submitted by  
Michael Berger,  
Barak Simoni


  ## 1. Setup a python environment on your computer (Pycharm / google colab).


  ## 2. Install the following libraries: pytorch, NLTK, spaCy

In [4]:
#conda install -y pytorch NLTK spaCy chardet


  ## 3. Write a program that loads the file spam.csv (source: KAGGLE)

In [19]:
import pandas as pd
import numpy as np
from IPython.display import Markdown, display
import re
import chardet

In [109]:
file = "data/spam.csv"
spam = pd.read_csv(file ,encoding='Windows-1252')

In [110]:

with open(file, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'Windows-1252', 'confidence': 0.7270322499829184, 'language': ''}

In [111]:
spam

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [112]:
spam[spam.iloc[:,2].notna()]

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
95,spam,Your free ringtone is waiting to be collected....,PO Box 5249,"MK17 92H. 450Ppw 16""",NaN
281,ham,\Wen u miss someone,the person is definitely special for u..... B...,why to miss them,"just Keep-in-touch\"" gdeve.."""
444,ham,\HEY HEY WERETHE MONKEESPEOPLE SAY WE MONKEYAR...,HOWU DOIN? FOUNDURSELF A JOBYET SAUSAGE?LOVE ...,NaN,NaN
671,spam,SMS. ac sun0819 posts HELLO:\You seem cool,"wanted to say hi. HI!!!\"" Stop? Send STOP to ...",NaN,NaN
710,ham,Height of Confidence: All the Aeronautics prof...,"this wont even start........ Datz confidence..""",NaN,NaN
899,spam,Your free ringtone is waiting to be collected....,PO Box 5249,"MK17 92H. 450Ppw 16""",NaN
1038,ham,"Edison has rightly said, \A fool can ask more ...",GN,GE,"GNT:-)"""
1127,ham,"Height of \Oh shit....!!\"" situation: A guy th...",".;-):-D""",NaN,NaN
1266,ham,\Hey sorry I didntgive ya a a bellearlier hunny,just been in bedbut mite go 2 thepub l8tr if u...,NaN,NaN
1384,ham,"Storming msg: Wen u lift d phne, u say \HELLO\...","bt not his girlfrnd... G o o d n i g h t . . .@""",NaN,NaN
1428,ham,"Tell you what, if you make a little spreadshee...","I'll come up""",NaN,NaN
1559,ham,Single line with a big meaning::::: \Miss anyt...,don't miss ur best life for anything... Gud n...,NaN,NaN
1637,spam,"0A$NETWORKS allow companies to bill for SMS, s...",just as a shop has to give a guarantee on wha...,NaN,NaN
1669,ham,Very hurting n meaningful lines ever: \I compr...,But at d end my love compromised me for every...,NaN,NaN
1675,ham,Painful words- \I thought being Happy was the ...,the toughest is acting Happy with all unspoke...,NaN,NaN
1936,ham,My planning usually stops at \find hella weed,"smoke hella weed\""""",NaN,NaN
1937,ham,The fact that you're cleaning shows you know w...,"\"" not \""what i need to do.\""""",NaN,NaN
1997,ham,\YEH I AM DEF UP4 SOMETHING SAT,JUST GOT PAYED2DAY & I HAVBEEN GIVEN Aå£50 PAY...,NaN,NaN
2087,ham,\alright babe,justthought iåÕd sayhey! how u doin?nearly th...,NaN,NaN
2170,ham,\CAN I PLEASE COME UP NOW IMIN TOWN.DONTMATTER...,JUST REALLYNEED 2DOCD.PLEASE DONTPLEASE DONTIG...,"U NO THECD ISV.IMPORTANT TOME 4 2MORO\""""",NaN
2235,ham,\Si.como no?!listened2the plaid album-quite gd...,"u hav2hear it!c u sn xxxx\""""",NaN,NaN
2255,ham,I just lov this line: \Hurt me with the truth,I don't mind,i wil tolerat.bcs ur my someone..... But,"Never comfort me with a lie\"" gud ni8 and swe..."
2406,ham,One of best dialogue in cute reltnship..!! \We...,Dont Come Near My Body..!! Bcoz My Hands May ...,NaN,NaN
2791,ham,"‰Û_ we r stayin here an extra week, back next ...",Well there's still a bit left if you guys want...,NaN,NaN
2970,ham,Height of Confidence: All the Aeronautics prof...,"this wont even start........ Datz confidence..""",NaN,NaN
3110,ham,Short But Cute : \ Be a good person,"but dont try to prove\"" ..... Gud mrng...""",NaN,NaN
3145,ham,\SHIT BABE.. THASA BIT MESSED UP.YEH,SHE SHUDVETOLD U. DID URGRAN KNOW?NEWAY,"ILLSPEAK 2 U2MORO WEN IM NOT ASLEEP...\""""",NaN
3239,ham,A cute thought for friendship: \Its not necess...,"but watever u shared should be true\""....""",NaN,NaN
3506,ham,Two fundamentals of cool life: \Walk,"like you are the KING\""...! OR \""Walk like yo...","whoever is the KING\""!... Gud nyt""",NaN
3525,ham,\HEY BABE! FAR 2 SPUN-OUT 2 SPK AT DA MO... DE...,HAD A COOL NYTHO,TX 4 FONIN HON,"CALL 2MWEN IM BK FRMCLOUD 9! J X\"""""
3547,ham,Single line with a big meaning::::: \Miss anyt...,don't miss ur best life for anything... Gud n...,NaN,NaN
3640,spam,You can stop further club tones by replying \S...,"PO Box 1146 MK45 2WT (2/3)""",NaN,NaN
3758,ham,"GOD ASKED, \What is forgiveness?\"" A little ch...","\""It is d wonderful fruit that a tree gives w...",NaN,NaN
3788,ham,Are you sure you don't mean \get here,"we made you hold all the weed\""""",NaN,NaN
3793,ham,Short But Cute: \Be a good person,"but dont try to prove it..\"" .Gud noon....""",NaN,NaN
3881,ham,Short But Cute: \Be a good person,"but dont try to prove it..\"" .Gud noon....""",NaN,NaN
4130,ham,\Its Ur luck to Love someone. Its Ur fortune t...,its a miracle to Love a person who can't Love...,NaN,NaN
4224,ham,\The world suffers a lot... Not because of the...,"Gud night....""",NaN,NaN
4454,ham,"Storming msg: Wen u lift d phne, u say \HELLO\...","bt not his girlfrnd... G o o d n i g h t . . .@""",NaN,NaN
4455,ham,If you want to mapquest it or something look u...,"that's the tiny street where the parking lot is""",NaN,NaN
4570,ham,\CHA QUITEAMUZING THATåÕSCOOL BABE,PROBPOP IN & CU SATTHEN HUNNY 4BREKKIE! LOVE J...,NaN,NaN
4601,ham,\Hey j! r u feeling any better,hopeSo hunny. i amnow feelin ill & ithink i m...,NaN,NaN
4668,ham,"When I was born, GOD said, \Oh No! Another IDI...",GOD said,"\""OH No! COMPETITION\"". Who knew","one day these two will become FREINDS FOREVER!"""
4859,ham,"\Response\"" is one of d powerful weapon 2 occu...","always give response 2 who cares 4 U\""... Gud...",NaN,NaN
4992,ham,\HEY KATE,HOPE UR OK... WILL GIVE U A BUZ WEDLUNCH. GO ...,NaN,NaN
5048,ham,"Edison has rightly said, \A fool can ask more ...",GN,GE,"GNT:-)"""
5079,ham,\Keep ur problems in ur heart,b'coz nobody will fight for u. Only u &amp; u...,NaN,NaN
5081,ham,\HI BABE UAWAKE?FEELLIKW SHIT.JUSTFOUND OUT VI...,DEVIOUSBITCH.ANYWAY,"IåÕL CALL U\""""",NaN
5264,ham,"Storming msg: Wen u lift d phne, u say \HELLO\...","bt not his girlfrnd... G o o d n i g h t . . .@""",NaN,NaN
5268,ham,\ER,ENJOYIN INDIANS AT THE MO..yeP. SaLL gOoD Heh...,NaN,NaN

Some messages got spread into several columns of the dataframe  
This happened due to inherent structure of messages, which contain all the possible characters,  
The presence of " and , chars in the messages makes separating tricky.  

We can solve it easily by concatenating the columns back into one column

In [113]:
spam.columns = "v1,v2,v3,v4,v5".split(",")
spam["msg"] = spam[['v2', 'v3', 'v4', 'v5']].fillna('').agg(", ".join, axis=1)
spam[["v1","msg"]]

        v1                                                msg
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                Ok lar... Joking wif u oni..., , ,
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham        Will Ì_ b going to esplanade fr home?, , ,
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                   Rofl. Its true to its name, , ,

[5572 rows x 2 columns]


  ## 4. Compute simple statistics on the data:

In [116]:

rows = spam.msg.apply(func=lambda n: re.split("[\d\W]+", n.lower()))
words = sum(rows.values.tolist(),[])

wordsPerMess = rows.apply(func = len)

unique, counts = np.unique(words, return_counts=True)
wc = pd.DataFrame({"token":unique, "count": counts})

tokens = wc.sort_values("count",ascending=False)

In [117]:
show = rows[:20].apply(lambda r:  " ".join(r))
print("\n".join(show))

go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat
ok lar joking wif u oni
free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s
u dun say so early hor u c already then say
nah i don t think he goes to usf he lives around here though
freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send å to rcv
even my brother is not like to speak with me they treat me like aids patent
as per your request melle melle oru minnaminunginte nurungu vettam has been set as your callertune for all callers press to copy your friends callertune
winner as a valued network customer you have been selected to receivea å prize reward to claim call claim code kl valid hours only
had your mobile months or more u r entitled to update to the latest colour mobiles with camera for free call the mobile update co free on
i m gonna be home soon and i don t want to talk about this stuff anymore tonight k i ve cried enough today
six chances to win cash from to pounds txt csh and send to cost p day days tsandcs apply reply hl info
urgent you have won a week free membership in our å prize jackpot txt the word claim to no t c www dbuk net lccltd pobox ldnw a rw
i ve been searching for the right words to thank you for this breather i promise i wont take your help for granted and will fulfil my promise you have been wonderful and a blessing at all times
i have a date on sunday with will
xxxmobilemovieclub to use your credit click the wap link in the next txt message or click here http wap xxxmobilemovieclub com n qjkgighjjgcbl
oh k i m watching here
eh u remember how spell his name yes i did he v naughty make until i v wet
fine if thatåõs the way u feel thatåõs the way its gota b
england v macedonia dont miss the goals team news txt ur national team to eg england to try wales scotland txt ì¼ poboxox w wq

In [118]:
ans = f"""
number of SMS messages: {spam.shape[0]},  
number of spams: {sum(spam.v1=="spam")},   
total word count: {len(words)},   
averaged number of words per message: {wordsPerMess.mean():.2f},   
5 most frequent words in the file: {tokens.token.head(5).values},   
number of rare words (appear only once in the file): {sum(tokens["count"] == 1)}.  
"""

display(Markdown(ans))

number of SMS messages: 5572,
number of spams: 747,
total word count: 93705,
averaged number of words per message: 16.82,
5 most frequent words in the file: ['' 'i' 'to' 'you' 'a'],
number of rare words (appear only once in the file): 3891.


  ## 5. Perform tokenization twice:

  ### a) by using NLTK library 
  
Barak

  ### b) and by Spacy library. 

Michael

In [121]:
from spacy.tokenizer import Tokenizer
from spacy.lang.en import English

tokenizer = Tokenizer(English().vocab)

spam["SpacyTokens"] = spam.msg.apply(func=tokenizer)
spam.SpacyTokens

0       (Go, until, jurong, point,, crazy.., Available...
1             (Ok, lar..., Joking, wif, u, oni...,, ,, ,)
2       (Free, entry, in, 2, a, wkly, comp, to, win, F...
3       (U, dun, say, so, early, hor..., U, c, already...
4       (Nah, I, don't, think, he, goes, to, usf,, he,...
                              ...
5567    (This, is, the, 2nd, time, we, have, tried, 2,...
5568    (Will, Ì_, b, going, to, esplanade, fr, home?,...
5569    (Pity,, *, was, in, mood, for, that., So...any...
5570    (The, guy, did, some, bitching, but, I, acted,...
5571             (Rofl., Its, true, to, its, name,, ,, ,)
Name: msg, Length: 5572, dtype: object

In [123]:
wat = spam.SpacyTokens[0]
wat

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..., , ,

  ### c) Write what is the difference between the results.


  ## 6. Perform lemmatization 
  by NLTK and  
  barak

  by Spacy libraries. 

Michael

  Write what is the difference between the results.


  ## 7. Perform stemming 
  by NLTK twice on both results of (6). Write what is the difference between the results.

Barak


  ## 8. Identify a spam message where its removal from the spam.csv dataset would:


  ### a)Reduce the total number of stemmed tokens
  
BArak


  ### b)Maintain the exact same number of lemmatized tokens
Michael

If no such message exists, provide a detailed explanation of why this scenario is
impossible or improbable.



  ## 9. Identify a spam message where its removal from the spam.csv dataset would:


  ### a)Reduce the total number of lemmatized tokens
  
Barak


  ### b)Maintain the exact same number of stemmed tokens

  Michael
If no such message exists, provide a detailed explanation of why this scenario is
impossible or improbable.



  ## 10. Compare the results of  
  NLTK before and after tokenization, lemmatization and stemming

  BArak


  ## 11. Compare the results of 
  Spacy before and after tokenization and lemmatization.

MIchael


  ## 12. Install the library BeautifulSoup


  ## 13. Choose any url page. 
  You can choose a page of yourself in a social media (e.g., facebook, Instagram, Linkdin, Twitter), or anything else


  ## 14. Perform data scrapping of this url. 
  You can learn how to do it from the following links:  
https://www.edureka.co/blog/web-scraping-with-python/  
https://zindi.africa/learn/a-beginners-guide-to-scraping-data-from-social-media  
or, ask CHATGPT to program it for you.  

Michael


  ## 15. Perform steps 5-11 on the text achieved in (14).


  ## 16. Download one of your whatsapp chats into *.txt file 
  (at least 50 messages in Hebrew).

  Barack


  ## 17. Repeat steps 5-11 on the text file achieved in (16)